{
  "media": "images",
  "collections": [
    {
      "name": "pages",
      "label": "Site Pages",
      "folder": "content",
      "path": "{{slug}}/{{slug}}",
      "extension": "md",
      "nested": true
    }
  ]
}