title: "Jak's Second Chance Rescue Ranch"
email: "jaksrescueranch@gmail.com"
description: "Saving dogs throughout Central Arkansas and helping them find loving forever homes."
markdown: kramdown
permalink: pretty